### ISSUE TITLE
0.0.13: No registered provider for type: DocumentRegistry.

### ISSUE THREAD

**Issue by cel4** [conda-forge/jupyterlab-feedstock#3]
version 0.0.13 does not seem to work for me on macOS.

`jupyter lab` fires up the browser, but does not load jupyterlab.

I get following error in both Safari and Chrome:

```
bundle.js:12586 Uncaught (in promise) Error: No registered provider for type: DocumentRegistry. Provider resolution path: .
    at missingProviderError (http://localhost:8889/lab/bundle.js:12586:17)
    at Object.resolveService (http://localhost:8889/lab/bundle.js:12535:36)
    at ServiceRegistry.resolveService (http://localhost:8889/lab/bundle.js:12441:25)
    at http://localhost:8889/lab/bundle.js:12284:75
    at Array.map (native)
    at ExtensionRegistry.activateExtension (http://localhost:8889/lab/bundle.js:12284:38)
    at Application.activateExtension (http://localhost:8889/lab/bundle.js:362:34)
    at http://localhost:8889/lab/bundle.js:431:73
    at Array.map (native)
    at http://localhost:8889/lab/bundle.js:431:40
```

**Comment by jasongrout** [comment]
Thanks. This was a subtle semver issue. I just bumped to 0.1.1, which should work.

**Comment by jasongrout** [comment]
I just checked, and it seems to work now.
