### ISSUE TITLE
post-link.sh fails when installing through conda constructor

### ISSUE THREAD

**Issue by Lucaszw** [conda-forge/jupyterlab-feedstock#85]
I am trying to build a conda constructor with the following construct.yaml file:
```yaml
name: Microdrop
version: 0.0.1

install_in_dependency_order: True

channels:
  - https://conda.anaconda.org/lucaszw
  - https://conda.anaconda.org/sci-bots
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/dfroger

specs:
  - python 3.5*
  - anaconda-client
  - nodejs 8*
  - jupyter_core
  - jupyter_client
  - jupyterlab

ignore_duplicate_files: True

installer_type: sh [osx]

post_install: post_install

license_file: LICENSE

welcome_image: welcome.png

```

Unfortunately, the install fails on os x with the following error message:

```bash
installing: jupyterlab-0.29.2-py35_0 ...
Error: post-link failed for: jupyterlab-0.29.2-py35_0
```

Calling the post-link command directly yields:

```python
Traceback (most recent call last):
  File "bin/jupyter-serverextension", line 4, in <module>
    import notebook.serverextensions
  File "/Users/lucaszw/microdrop/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Users/lucaszw/microdrop/lib/python3.5/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ImportError: No module named 'jupyter_core'
```

**Comment by jakirkham** [comment]
Please raise over at [`constructor`]( https://github.com/conda/constructor ). Thanks.

**Comment by jakirkham** [comment]
Note: This was opened upstream as issue ( https://github.com/conda/constructor/issues/144 ).
